name: CI

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Output image tag'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -ldflags="-X 'github.com/techgarage-ir/IP-Hub/config.Version=${{ github.ref_name }}' -X 'github.com/techgarage-ir/IP-Hub/config.BaseSource=${{ secrets.LOOKUP_SOURCE }}' -s -w" -trimpath -o /dist/app

      - name: Build plugins
        run: |
          for f in plugins/*/*.go; do \
            echo "Building $f"; \
            go build -buildmode=plugin -ldflags='-s -w' -trimpath -o "/dist/${f%.go}.so" "$f"; \
          done

      - name: Define Tags
        id: define-tags
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "ghcr.io/${{ github.repository_owner }}/IP-Hub:${{ github.ref_name }}, ghcr.io/${{ github.repository_owner }}/IP-Hub:latest" >> $GITHUB_ENV
          else
            echo "ghcr.io/${{ github.repository_owner }}/IP-Hub:${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        env:
          GHCR_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/IP-Hub"
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.tags }}
